# ===== Flywayなし（保険）=====

#spring.flyway.enabled=false

#spring.sql.init.mode=always
#spring.sql.init.schema-locations=classpath:/init/schema.sql
#spring.sql.init.data-locations=classpath:/init/data.sql

#spring.jpa.hibernate.ddl-auto=none